Vozzhd/practicum-android-diploma

app/build.gradle.kts, gradle/libs.versions.toml
Минимальный SDK согласно ТЗ установлен - 26.
Версии описаны в libs.versions.toml
=> Добавлены библиотеки и зависимости для проекта.

app/src/main/AndroidManifest.xml, app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/res/layout/activity_root.xml
Изменена структура проекта на "разделение по фичам", добавлены файлы для DI
=> Изменена структура проекта

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/util/App.kt, gradle/libs.versions.toml
Добавил версию koin для корректной работы, добавил файл App.
Добавил запуск koin с модулями, описал модули в файлах
=> Koin & DI done

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/util/App.kt
Добавил константу SHARED_PREFS для удобства доступа
=> Добавил в DI SharedPreferencies

app/src/main/AndroidManifest.xml, app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/favorite/ui/FavoriteFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/CitySelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/CountrySelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/FilterSettingsFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/IndustrySelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/WorkingRegionFragment.kt, app/src/main/java/ru/practicum/android/diploma/info/ui/InfoFragment.kt, app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyFragment.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/city_select_fragment.xml, app/src/main/res/layout/country_select_fragment.xml, app/src/main/res/layout/favorite_fragment.xml, app/src/main/res/layout/filter_settings_fragment.xml, app/src/main/res/layout/industry_select_fragment.xml, app/src/main/res/layout/info_fragment.xml, app/src/main/res/layout/search_fragment.xml, app/src/main/res/layout/vacancy_fragment.xml, app/src/main/res/layout/working_region_fragment.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
=> Diploma 27

app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
Добавил цвета,
Добавил размеры
и Стили
=> Создал стили ,

app/src/main/java/ru/practicum/android/diploma/database/converters/VacancyDbConverter.kt, app/src/main/java/ru/practicum/android/diploma/database/dao/VacancyDetailsDao.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/favorite/data/FavoriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/api/FavoriteVacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/api/FavoriteVacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/impl/FavoriteVacancyInteractorImpl.kt
Добавлен конвертер
Немного изменил дао Функции
Сделаны репозитории и Интеракторы и добавлены в DI
=> Реализация методов Избранных вакансий

app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchScreenState.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/VacancySearchFragment.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/vacancy_search_fragment.xml
=> DIPLOMA-96-Pagination

app/src/main/java/ru/practicum/android/diploma/favorite/presintation/FavoriteVacancyViewModel.kt, app/src/main/java/ru/practicum/android/diploma/favorite/ui/FavoriteFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/data/impl/GetVacancyDetailsRepositoryImpl.kt
=> Поправил detekt и код отправки запроса на детали вакансии

app/src/main/java/ru/practicum/android/diploma/search/data/converters/SearchVacancyNetworkConverter.kt, app/src/main/java/ru/practicum/android/diploma/search/data/impl/SearchVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchVacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchVacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/impl/SearchVacancyInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/models/VacancyListResponseData.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchScreenState.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/VacancySearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/util/PluralsFormat.kt, app/src/main/res/drawable/search_state_message_background.xml, app/src/main/res/layout/vacancy_card.xml, app/src/main/res/layout/vacancy_search_fragment.xml, app/src/main/res/values/plurals.xml, app/src/main/res/values/strings.xml
Добавил синее окно на экране поиска
Изменил возвращаемый из data объект
Правки по интерфейсу
Поправил загрузку пагинации
Убрал задержку у клика по элементу списка
=> Diploma 112 blue button search screen

app/src/main/java/ru/practicum/android/diploma/database/dao/VacancyDetailsDao.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/favorite/data/FavoriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/api/FavoriteVacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/api/FavoriteVacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/impl/FavoriteVacancyInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/data/impl/GetVacancyDetailsRepositoryImpl.kt
2-Обновлен запрос для Деталей вакансии исходя из ТЗ
=> 1-Добавлен метод Обновления вакансии в БД

app/src/main/java/ru/practicum/android/diploma/database/converters/VacancyDbConverter.kt, app/src/main/java/ru/practicum/android/diploma/database/entities/VacancyDetailsEntity.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/data/converter/VacancyDetailsNetworkConverter.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/data/network/VacancyDetailsResponse.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/domain/entity/Vacancy.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/VacancyDetailsViewModel.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyDetailFragment.kt
Добавлена реализация кнопки `поделиться` на экране деталей вакансии
=> 126 share button

app/src/main/res/layout/vacancy_detail_fragment.xml
Поправил xml файл. Вакансия теперь отображается верно
=> Исправил отображение описания вакансии

app/src/main/res/drawable/border_corner_12dp_light_grey.xml, app/src/main/res/layout/vacancy_card.xml
Добавил рамку логотипов компаний в окне поиска
=> Diploma 121 icon border

app/src/main/java/ru/practicum/android/diploma/filters/ui/FilterSettingsFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/VacancySearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyDetailFragment.kt, app/src/main/res/drawable/ic_arrow_forward_24px.xml, app/src/main/res/layout/filter_settings_fragment.xml, app/src/main/res/layout/working_region_fragment.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Взял ветку от свой с версткой экрана настройки фильтров. Можно смотреть только последний комит
=> Diploma 149 job place screen

app/src/main/java/ru/practicum/android/diploma/favorite/ui/FavoriteFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/data/converters/SearchVacancyNetworkConverter.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchScreenState.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/VacancySearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/presenter/RecycleViewAdapter.kt
=> Bug fix refactor search screen

app/src/main/java/ru/practicum/android/diploma/filters/ui/CitySelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/CountrySelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/FilterSettingsFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/ui/WorkingRegionFragment.kt, app/src/main/res/layout/city_select_fragment.xml, app/src/main/res/layout/filter_settings_fragment.xml, app/src/main/res/layout/working_region_fragment.xml, app/src/main/res/values/strings.xml
Оставил граф навигации таким каким он был раньше. Тк под него уже есь вся верстка. добавил clickListener для переходов между всеми имеющимися экранами и реализовал toolBarNavigation там, где он есть.
Также поправил вёрстку
=> Добавление навигации и правка вёрстки

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/areas/ui/CountrySelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/presentation/CountrySelectViewModel.kt, app/src/main/res/navigation/navigation_graph.xml
При нажатие на страну ее id сохраняется в ШаредПреф
=> Сохранение area.id в sharedPref

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/areas/presentation/AreaSelectViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/areas/ui/AreaSelectFragment.kt, app/src/main/res/layout/area_select_fragment.xml
Есть закомментированный код, и функции без реализации. стоят TODO которые просто ничего не делают
=> Diploma 203 Скелет для отображения фильтра (страна регион) на экране страны и региона, + viewModel 

app/src/main/java/ru/practicum/android/diploma/filters/base/presentation/FilterSettingsViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/base/ui/FilterSettingsFragment.kt
Созранение параметров после нажатия применить
=> Сохранение и инициализация ЗП

app/src/main/java/ru/practicum/android/diploma/filters/areas/ui/RegionSelectFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchViewModel.kt
Если набрать поиск региона, удалить текст, то полный список теперь показывается
=> 238 поиск региона исправил баг

app/src/main/java/ru/practicum/android/diploma/filters/industries/domain/models/Industry.kt, app/src/main/java/ru/practicum/android/diploma/filters/industries/presentation/IndustrySelectViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/industries/ui/presenter/IndustrySelectRecyclerViewAdapter.kt
-показать полный список индустрий при очистке строки поиска 
-показать выбранной позицию из sharedprefs
=> обновление списка индустрий+отображение выбранной отрасли
